#!/usr/bin/env python3
import os


def list_files_and_contents(
    startpath,
    output_file,
    ignored_dirs=None,
    ignored_files=None,
    ignored_extensions=None,
):
    # Default ignored directories (tuned for JS/Next.js projects)
    if ignored_dirs is None:
        ignored_dirs = [
            "node_modules",
            ".next",      # Next.js build output
            ".turbo",     # Turborepo cache
            ".git",
            ".vercel",    # Vercel metadata
            "coverage",
            "dist",
            "build",
            "out",        # next export
            ".vscode",
            ".idea",
            ".husky",
        ]

    # Default ignored files (common lock/config/junk)
    if ignored_files is None:
        ignored_files = [
            output_file,
            "package-lock.json",
            "pnpm-lock.yaml",
            "yarn.lock",
            ".gitignore",
            ".gitattributes",
            ".DS_Store",
            ".env",
            ".env.local",
            ".env.development",
            ".env.production",
            ".env.test",
            "next-env.d.ts",  # auto-generated by Next
        ]

    # Default ignored extensions (big / noisy / usually not needed in text dump)
    if ignored_extensions is None:
        ignored_extensions = [
            ".log",
            ".map",
            ".lock",
            ".ico",
            ".png",
            ".jpg",
            ".jpeg",
            ".gif",
            ".webp",
            ".svg",
            ".mp4",
            ".mp3",
            ".woff",
            ".woff2",
            ".ttf",
            ".eot",
        ]

    def should_ignore_file(filename):
        if filename in ignored_files:
            return True
        _, ext = os.path.splitext(filename)
        return ext in ignored_extensions

    with open(output_file, "w", encoding="utf-8") as out:
        # ---------- 1) Directory structure ----------
        for root, dirs, files in os.walk(startpath):
            # Skip ignored directories
            dirs[:] = [d for d in dirs if d not in ignored_dirs]

            # Filter files
            files = [f for f in files if not should_ignore_file(f)]

            level = root.replace(startpath, "").count(os.sep)
            indent = " " * 4 * level
            out.write(f"{indent}└── {os.path.basename(root)}/\n")

            subindent = " " * 4 * (level + 1)
            for f in files:
                out.write(f"{subindent}└── {f}\n")

        out.write("\n")

        # ---------- 2) File contents ----------
        for root, dirs, files in os.walk(startpath):
            dirs[:] = [d for d in dirs if d not in ignored_dirs]
            files = [f for f in files if not should_ignore_file(f)]

            for f in files:
                file_path = os.path.join(root, f)
                relative_path = os.path.relpath(file_path, startpath)
                out.write(f"Contents of {relative_path}:\n\n")
                try:
                    with open(file_path, "r", encoding="utf-8") as file:
                        content = file.read()
                        out.write(content + "\n")
                except UnicodeDecodeError:
                    out.write(
                        f"Could not read {relative_path} due to encoding issues.\n"
                    )
                out.write("\n")


# Example usage for a Next.js project:
ignored_dirs = [
    "node_modules",
    ".next",
    ".turbo",
    ".git",
    ".vercel",
    "coverage",
    "dist",
    "build",
    "out",
    ".vscode",
    ".idea",
    ".husky",
]

ignored_files = [
    "output_structure.txt",
    "package-lock.json",
    "pnpm-lock.yaml",
    "yarn.lock",
    ".gitignore",
    ".gitattributes",
    ".DS_Store",
    ".env",
    ".env.local",
    ".env.development",
    ".env.production",
    ".env.test",
    "next-env.d.ts",
]

ignored_extensions = [
    ".log",
    ".map",
    ".lock",
    ".ico",
    ".png",
    ".jpg",
    ".jpeg",
    ".gif",
    ".webp",
    ".svg",
    ".mp4",
    ".mp3",
    ".woff",
    ".woff2",
    ".ttf",
    ".eot",
]

output_file = "output_structure.txt"

list_files_and_contents(
    ".",
    output_file,
    ignored_dirs=ignored_dirs,
    ignored_files=ignored_files,
    ignored_extensions=ignored_extensions,
)

print(f"Output has been written to {output_file}")
